name:                  Docs
on:
  push:
    branches:          [main]
jobs:
  build_docs:
    runs-on:           ubuntu-latest
    steps:
      - name:          checkout repo
        uses:          actions/checkout@v4
        with:
          fetch-depth: 1
      - name:          setup python
        uses:          actions/setup-python@v5
        with:
          python-version: 3.11
      - name:          build docs
        run:           make docs
      - name:          upload docs
        uses:          actions/upload-pages-artifact@v3
        with:
          path:        docs/
  deploy_docs:
    runs-on:           ubuntu-latest
    needs:             build_docs
    permissions:
      pages:           write
      id-token:        write
    environment:
      name:            github-pages
      url:             ${{ steps.deployment.outputs.page_url }}
    steps:
      - name:          deploy docs
        id:            deployment
        uses:          actions/deploy-pages@v4
