name: publish release

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: publish release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/decoding
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: build package
        run: |
          python setup.py sdist bdist_wheel
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
